apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-templates
spec:
  type: url
  targets:
    - https://github.com/not-lob/backstage-templates/blob/main/spring-boot-template/template.yaml